# Generated by Django 4.2.19 on 2025-02-06 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('aisle_id', models.AutoField(primary_key=True, serialize=False)),
                ('aisle', models.CharField(max_length=50, unique=True, verbose_name='aisle')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=50, unique=True, verbose_name='department')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('eval_set', models.CharField(max_length=50)),
                ('order_number', models.IntegerField()),
                ('order_dow', models.IntegerField()),
                ('order_hour_of_day', models.IntegerField()),
                ('days_since_prior_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50, unique=True, verbose_name='product_name')),
                ('aisle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.aisle')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.department')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_to_cart_order', models.IntegerField()),
                ('reordered', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.user'),
        ),
    ]
