# Generated by Django 4.2.19 on 2025-02-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_alter_department_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='product_name'),
        ),
    ]
