# Generated by Django 4.2.19 on 2025-02-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_alter_aisle_aisle_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
