# Generated by Django 4.2.19 on 2025-02-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0005_alter_order_user_id_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisle',
            name='aisle',
            field=models.CharField(max_length=150, verbose_name='aisle'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=200, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='order',
            name='eval_set',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=250, verbose_name='product_name'),
        ),
    ]
